### ISSUE TITLE
(Minor Issue) Readme.md images are too large!

### ISSUE THREAD

**Issue by KhounborineII** [KhounborineII/to-do-list-khounborine#4]
Could someone resize those for me? Could be worth it as a small pull request.

**Comment by garrettcollier** [comment]
@KhounborineII I can take this on

**Comment by KhounborineII** [comment]
@garrettcollier All yours!

**Comment by garrettcollier** [comment]
This change has been made along with some other code updates to remove warnings and issues on my end when running. Let me  know what you think @KhounborineII
